paths:
  train_csv: data/train.csv
  test_csv: data/test.csv
  target_order: ["dia", "chl", "cya", "coc", "din", "pha", "tot_chla"]
bands: pace_like
cv: {seed: 42, n_splits: 5, test_size: 0.2}
xgb: {n_estimators: 800, max_depth: 8, learning_rate: 0.05, subsample: 0.8, colsample_bytree: 0.8, gamma: 0.0, reg_lambda: 1.0, reg_alpha: 0.0, random_state: 42}
optuna: {enabled: false, n_trials: 100, timeout_min: null, storage: null}